server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/local?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    consul:
      host: localhost
      port: 8500

mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.jason.lee.entities
